debug: true

api:
  base: 'https://blocklevel.nl/api'
facebook:
  key: 1478098066847
  secret: 1478098066847
favicon:
  path: 'static/image/favicon.png'
  out: 'static/favicons/icon-[hash]'
  background: '#fff'
